// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Cars struct {
	ID            int32     `json:"id"`
	Title         string    `json:"title"`
	ModelID       string    `json:"model_id"`
	ModelName     string    `json:"model_name"`
	OwnerID       int32     `json:"owner_id"`
	Color         string    `json:"color"`
	Description   string    `json:"description"`
	Tags          []string  `json:"tags"`
	Images        []string  `json:"images"`
	Metadata      []string  `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	ModifiedAt    time.Time `json:"modified_at"`
	ListingStatus string    `json:"listing_status"`
	OwnerUsername string    `json:"owner_username"`
}

type Sessions struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Users struct {
	ID              int32     `json:"id"`
	Username        string    `json:"username"`
	HashedPassword  string    `json:"hashed_password"`
	FullName        string    `json:"full_name"`
	Email           string    `json:"email"`
	Role            string    `json:"role"`
	CreatedAt       time.Time `json:"created_at"`
	IsEmailVerified bool      `json:"is_email_verified"`
}

type VerifyEmails struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
